// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project3MVC.Models;

#nullable disable

namespace Project3MVC.Migrations
{
    [DbContext(typeof(Proj3Context))]
    [Migration("20241117222330_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project3MVC.Models.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description of Forum 1",
                            Name = "Forum1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description of Forum 2",
                            Name = "Forum2"
                        });
                });

            modelBuilder.Entity("Project3MVC.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForumId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("isReply")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ForumId = 1,
                            ParentId = 0,
                            TextContent = "User1 posting on Forum 1",
                            UserId = 1,
                            isReply = false
                        },
                        new
                        {
                            Id = 2,
                            ForumId = 2,
                            ParentId = 0,
                            TextContent = "User1 posting on Forum 2",
                            UserId = 1,
                            isReply = false
                        },
                        new
                        {
                            Id = 3,
                            ForumId = 1,
                            ParentId = 0,
                            TextContent = "User2 posting on Forum 1",
                            UserId = 2,
                            isReply = false
                        },
                        new
                        {
                            Id = 4,
                            ForumId = 2,
                            ParentId = 0,
                            TextContent = "User2 posint on Forum 2",
                            UserId = 2,
                            isReply = false
                        });
                });

            modelBuilder.Entity("Project3MVC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Username = "User1",
                            email = "User1@localhost.port",
                            password = "password"
                        },
                        new
                        {
                            Id = 2,
                            Username = "User2",
                            email = "User2@localhost.port",
                            password = "password"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
